# Generated by Django 3.1.6 on 2021-02-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=7)),
                ('pizza_size', models.CharField(blank=True, choices=[('large', 'large'), ('small', 'small'), ('medium', 'medium'), ('extra large', 'extra large')], max_length=12)),
                ('pizza_toppings', models.ManyToManyField(blank=True, to='pizza.Topping')),
            ],
        ),
    ]
