# Generated by Django 3.0.5 on 2021-05-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=7)),
                ('pizza_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.PizzaSize')),
                ('pizza_toppings', models.ManyToManyField(blank=True, to='pizza.Topping')),
            ],
        ),
    ]
