# Generated by Django 3.1.6 on 2021-02-07 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20210206_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='pizza_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizzasize'),
        ),
    ]
